version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/provider"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/sdk/nodejs"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    commit-message:
      prefix: "ci"
