version: "2"

run:
  timeout: 20m

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
  exclusions:
    paths:
      - schema.go
      - pulumiManifest.go

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - schema.go
      - pulumiManifest.go
