version: 2
before:
  hooks:
    - make provider
builds:
  - binary: pulumi-resource-rootly
    dir: provider
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - '-s -w -X github.com/rootlyhq/pulumi-rootly/provider/pkg/version.Version={{.Version}}'
    main: ./cmd/pulumi-resource-rootly/
archives:
  - id: archive
    format: zip
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    files:
      - 'none*'
checksum:
  name_template: 'pulumi-resource-rootly_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
changelog:
  disable: true
release:
  disable: false
  prerelease: auto
snapshot:
  version_template: '{{ .Tag }}-SNAPSHOT'
