// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rootly
{
    [RootlyResourceType("rootly:index/postMortemTemplate:PostMortemTemplate")]
    public partial class PostMortemTemplate : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The postmortem template. Liquid syntax and markdown are supported
        /// </summary>
        [Output("content")]
        public Output<string> Content { get; private set; } = null!;

        /// <summary>
        /// Default selected template when editing a postmortem. Value must be one of true or false
        /// </summary>
        [Output("default")]
        public Output<bool> Default { get; private set; } = null!;

        /// <summary>
        /// The format of the input. Value must be one of `html`, `markdown`.
        /// </summary>
        [Output("format")]
        public Output<string?> Format { get; private set; } = null!;

        /// <summary>
        /// The name of the postmortem template
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a PostMortemTemplate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PostMortemTemplate(string name, PostMortemTemplateArgs? args = null, CustomResourceOptions? options = null)
            : base("rootly:index/postMortemTemplate:PostMortemTemplate", name, args ?? new PostMortemTemplateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PostMortemTemplate(string name, Input<string> id, PostMortemTemplateState? state = null, CustomResourceOptions? options = null)
            : base("rootly:index/postMortemTemplate:PostMortemTemplate", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/rootlyhq/pulumi-rootly/releases/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PostMortemTemplate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PostMortemTemplate Get(string name, Input<string> id, PostMortemTemplateState? state = null, CustomResourceOptions? options = null)
        {
            return new PostMortemTemplate(name, id, state, options);
        }
    }

    public sealed class PostMortemTemplateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The postmortem template. Liquid syntax and markdown are supported
        /// </summary>
        [Input("content")]
        public Input<string>? Content { get; set; }

        /// <summary>
        /// Default selected template when editing a postmortem. Value must be one of true or false
        /// </summary>
        [Input("default")]
        public Input<bool>? Default { get; set; }

        /// <summary>
        /// The format of the input. Value must be one of `html`, `markdown`.
        /// </summary>
        [Input("format")]
        public Input<string>? Format { get; set; }

        /// <summary>
        /// The name of the postmortem template
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public PostMortemTemplateArgs()
        {
        }
        public static new PostMortemTemplateArgs Empty => new PostMortemTemplateArgs();
    }

    public sealed class PostMortemTemplateState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The postmortem template. Liquid syntax and markdown are supported
        /// </summary>
        [Input("content")]
        public Input<string>? Content { get; set; }

        /// <summary>
        /// Default selected template when editing a postmortem. Value must be one of true or false
        /// </summary>
        [Input("default")]
        public Input<bool>? Default { get; set; }

        /// <summary>
        /// The format of the input. Value must be one of `html`, `markdown`.
        /// </summary>
        [Input("format")]
        public Input<string>? Format { get; set; }

        /// <summary>
        /// The name of the postmortem template
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public PostMortemTemplateState()
        {
        }
        public static new PostMortemTemplateState Empty => new PostMortemTemplateState();
    }
}
