// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rootly
{
    [RootlyResourceType("rootly:index/retrospectiveProcess:RetrospectiveProcess")]
    public partial class RetrospectiveProcess : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Retrospective process ID from which retrospective steps have to be copied. To use starter template for retrospective steps provide value: 'starter_template'
        /// </summary>
        [Output("copyFrom")]
        public Output<string?> CopyFrom { get; private set; } = null!;

        /// <summary>
        /// The description of the retrospective process
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Is the retrospective process default?. Value must be one of true or false
        /// </summary>
        [Output("isDefault")]
        public Output<bool> IsDefault { get; private set; } = null!;

        /// <summary>
        /// The name of the retrospective process
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("retrospectiveProcessMatchingCriteria")]
        public Output<Outputs.RetrospectiveProcessRetrospectiveProcessMatchingCriteria> RetrospectiveProcessMatchingCriteria { get; private set; } = null!;


        /// <summary>
        /// Create a RetrospectiveProcess resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RetrospectiveProcess(string name, RetrospectiveProcessArgs args, CustomResourceOptions? options = null)
            : base("rootly:index/retrospectiveProcess:RetrospectiveProcess", name, args ?? new RetrospectiveProcessArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RetrospectiveProcess(string name, Input<string> id, RetrospectiveProcessState? state = null, CustomResourceOptions? options = null)
            : base("rootly:index/retrospectiveProcess:RetrospectiveProcess", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/rootlyhq/pulumi-rootly/releases/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RetrospectiveProcess resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RetrospectiveProcess Get(string name, Input<string> id, RetrospectiveProcessState? state = null, CustomResourceOptions? options = null)
        {
            return new RetrospectiveProcess(name, id, state, options);
        }
    }

    public sealed class RetrospectiveProcessArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Retrospective process ID from which retrospective steps have to be copied. To use starter template for retrospective steps provide value: 'starter_template'
        /// </summary>
        [Input("copyFrom")]
        public Input<string>? CopyFrom { get; set; }

        /// <summary>
        /// The description of the retrospective process
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Is the retrospective process default?. Value must be one of true or false
        /// </summary>
        [Input("isDefault")]
        public Input<bool>? IsDefault { get; set; }

        /// <summary>
        /// The name of the retrospective process
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("retrospectiveProcessMatchingCriteria", required: true)]
        public Input<Inputs.RetrospectiveProcessRetrospectiveProcessMatchingCriteriaArgs> RetrospectiveProcessMatchingCriteria { get; set; } = null!;

        public RetrospectiveProcessArgs()
        {
        }
        public static new RetrospectiveProcessArgs Empty => new RetrospectiveProcessArgs();
    }

    public sealed class RetrospectiveProcessState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Retrospective process ID from which retrospective steps have to be copied. To use starter template for retrospective steps provide value: 'starter_template'
        /// </summary>
        [Input("copyFrom")]
        public Input<string>? CopyFrom { get; set; }

        /// <summary>
        /// The description of the retrospective process
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Is the retrospective process default?. Value must be one of true or false
        /// </summary>
        [Input("isDefault")]
        public Input<bool>? IsDefault { get; set; }

        /// <summary>
        /// The name of the retrospective process
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("retrospectiveProcessMatchingCriteria")]
        public Input<Inputs.RetrospectiveProcessRetrospectiveProcessMatchingCriteriaGetArgs>? RetrospectiveProcessMatchingCriteria { get; set; }

        public RetrospectiveProcessState()
        {
        }
        public static new RetrospectiveProcessState Empty => new RetrospectiveProcessState();
    }
}
