// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rootly.Outputs
{

    [OutputType]
    public sealed class GetIncidentRolesIncidentRoleResult
    {
        public readonly string Description;
        public readonly bool Enabled;
        public readonly string Id;
        public readonly string Name;
        public readonly string Slug;
        public readonly string Summary;

        [OutputConstructor]
        private GetIncidentRolesIncidentRoleResult(
            string description,

            bool enabled,

            string id,

            string name,

            string slug,

            string summary)
        {
            Description = description;
            Enabled = enabled;
            Id = id;
            Name = name;
            Slug = slug;
            Summary = summary;
        }
    }
}
