// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rootly.Outputs
{

    [OutputType]
    public sealed class WorkflowTaskGeniusCreateOpenaiChatCompletionTaskParams
    {
        /// <summary>
        /// Map must contain two fields, `Id` and `Name`. The OpenAI model. eg: gpt-4o-mini
        /// </summary>
        public readonly ImmutableDictionary<string, string> Model;
        /// <summary>
        /// The prompt to send to OpenAI
        /// </summary>
        public readonly string Prompt;
        public readonly string? TaskType;

        [OutputConstructor]
        private WorkflowTaskGeniusCreateOpenaiChatCompletionTaskParams(
            ImmutableDictionary<string, string> model,

            string prompt,

            string? taskType)
        {
            Model = model;
            Prompt = prompt;
            TaskType = taskType;
        }
    }
}
