// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rootly

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rootlyhq/pulumi-rootly/sdk/v3/go/rootly/internal"
)

// ## Example Usage
func LookupFunctionality(ctx *pulumi.Context, args *LookupFunctionalityArgs, opts ...pulumi.InvokeOption) (*LookupFunctionalityResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFunctionalityResult
	err := ctx.Invoke("rootly:index/getFunctionality:getFunctionality", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFunctionality.
type LookupFunctionalityArgs struct {
	BackstageId *string `pulumi:"backstageId"`
	CortexId    *string `pulumi:"cortexId"`
	// Filter by date range using 'lt' and 'gt'.
	CreatedAt  map[string]string `pulumi:"createdAt"`
	ExternalId *string           `pulumi:"externalId"`
	Name       *string           `pulumi:"name"`
	Slug       *string           `pulumi:"slug"`
}

// A collection of values returned by getFunctionality.
type LookupFunctionalityResult struct {
	BackstageId string `pulumi:"backstageId"`
	CortexId    string `pulumi:"cortexId"`
	// Filter by date range using 'lt' and 'gt'.
	CreatedAt  map[string]string `pulumi:"createdAt"`
	ExternalId string            `pulumi:"externalId"`
	// The ID of this resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
	Slug string `pulumi:"slug"`
}

func LookupFunctionalityOutput(ctx *pulumi.Context, args LookupFunctionalityOutputArgs, opts ...pulumi.InvokeOption) LookupFunctionalityResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupFunctionalityResultOutput, error) {
			args := v.(LookupFunctionalityArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("rootly:index/getFunctionality:getFunctionality", args, LookupFunctionalityResultOutput{}, options).(LookupFunctionalityResultOutput), nil
		}).(LookupFunctionalityResultOutput)
}

// A collection of arguments for invoking getFunctionality.
type LookupFunctionalityOutputArgs struct {
	BackstageId pulumi.StringPtrInput `pulumi:"backstageId"`
	CortexId    pulumi.StringPtrInput `pulumi:"cortexId"`
	// Filter by date range using 'lt' and 'gt'.
	CreatedAt  pulumi.StringMapInput `pulumi:"createdAt"`
	ExternalId pulumi.StringPtrInput `pulumi:"externalId"`
	Name       pulumi.StringPtrInput `pulumi:"name"`
	Slug       pulumi.StringPtrInput `pulumi:"slug"`
}

func (LookupFunctionalityOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFunctionalityArgs)(nil)).Elem()
}

// A collection of values returned by getFunctionality.
type LookupFunctionalityResultOutput struct{ *pulumi.OutputState }

func (LookupFunctionalityResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFunctionalityResult)(nil)).Elem()
}

func (o LookupFunctionalityResultOutput) ToLookupFunctionalityResultOutput() LookupFunctionalityResultOutput {
	return o
}

func (o LookupFunctionalityResultOutput) ToLookupFunctionalityResultOutputWithContext(ctx context.Context) LookupFunctionalityResultOutput {
	return o
}

func (o LookupFunctionalityResultOutput) BackstageId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionalityResult) string { return v.BackstageId }).(pulumi.StringOutput)
}

func (o LookupFunctionalityResultOutput) CortexId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionalityResult) string { return v.CortexId }).(pulumi.StringOutput)
}

// Filter by date range using 'lt' and 'gt'.
func (o LookupFunctionalityResultOutput) CreatedAt() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupFunctionalityResult) map[string]string { return v.CreatedAt }).(pulumi.StringMapOutput)
}

func (o LookupFunctionalityResultOutput) ExternalId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionalityResult) string { return v.ExternalId }).(pulumi.StringOutput)
}

// The ID of this resource.
func (o LookupFunctionalityResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionalityResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFunctionalityResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionalityResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupFunctionalityResultOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFunctionalityResult) string { return v.Slug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFunctionalityResultOutput{})
}
