// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rootly

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rootlyhq/pulumi-rootly/sdk/v3/go/rootly/internal"
)

// ## Example Usage
func LookupFormField(ctx *pulumi.Context, args *LookupFormFieldArgs, opts ...pulumi.InvokeOption) (*LookupFormFieldResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFormFieldResult
	err := ctx.Invoke("rootly:index/getFormField:getFormField", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFormField.
type LookupFormFieldArgs struct {
	// Filter by date range using 'lt' and 'gt'.
	CreatedAt map[string]string `pulumi:"createdAt"`
	Enabled   *bool             `pulumi:"enabled"`
	Kind      *string           `pulumi:"kind"`
	Name      *string           `pulumi:"name"`
	Slug      *string           `pulumi:"slug"`
}

// A collection of values returned by getFormField.
type LookupFormFieldResult struct {
	// Filter by date range using 'lt' and 'gt'.
	CreatedAt map[string]string `pulumi:"createdAt"`
	Enabled   *bool             `pulumi:"enabled"`
	// The ID of this resource.
	Id   string `pulumi:"id"`
	Kind string `pulumi:"kind"`
	Name string `pulumi:"name"`
	Slug string `pulumi:"slug"`
}

func LookupFormFieldOutput(ctx *pulumi.Context, args LookupFormFieldOutputArgs, opts ...pulumi.InvokeOption) LookupFormFieldResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupFormFieldResult, error) {
			args := v.(LookupFormFieldArgs)
			r, err := LookupFormField(ctx, &args, opts...)
			var s LookupFormFieldResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupFormFieldResultOutput)
}

// A collection of arguments for invoking getFormField.
type LookupFormFieldOutputArgs struct {
	// Filter by date range using 'lt' and 'gt'.
	CreatedAt pulumi.StringMapInput `pulumi:"createdAt"`
	Enabled   pulumi.BoolPtrInput   `pulumi:"enabled"`
	Kind      pulumi.StringPtrInput `pulumi:"kind"`
	Name      pulumi.StringPtrInput `pulumi:"name"`
	Slug      pulumi.StringPtrInput `pulumi:"slug"`
}

func (LookupFormFieldOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFormFieldArgs)(nil)).Elem()
}

// A collection of values returned by getFormField.
type LookupFormFieldResultOutput struct{ *pulumi.OutputState }

func (LookupFormFieldResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFormFieldResult)(nil)).Elem()
}

func (o LookupFormFieldResultOutput) ToLookupFormFieldResultOutput() LookupFormFieldResultOutput {
	return o
}

func (o LookupFormFieldResultOutput) ToLookupFormFieldResultOutputWithContext(ctx context.Context) LookupFormFieldResultOutput {
	return o
}

// Filter by date range using 'lt' and 'gt'.
func (o LookupFormFieldResultOutput) CreatedAt() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupFormFieldResult) map[string]string { return v.CreatedAt }).(pulumi.StringMapOutput)
}

func (o LookupFormFieldResultOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupFormFieldResult) *bool { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// The ID of this resource.
func (o LookupFormFieldResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFormFieldResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFormFieldResultOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFormFieldResult) string { return v.Kind }).(pulumi.StringOutput)
}

func (o LookupFormFieldResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFormFieldResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupFormFieldResultOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFormFieldResult) string { return v.Slug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFormFieldResultOutput{})
}
