// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rootly

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rootlyhq/pulumi-rootly/sdk/v3/go/rootly/internal"
)

func GetIncidentTypes(ctx *pulumi.Context, args *GetIncidentTypesArgs, opts ...pulumi.InvokeOption) (*GetIncidentTypesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetIncidentTypesResult
	err := ctx.Invoke("rootly:index/getIncidentTypes:getIncidentTypes", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIncidentTypes.
type GetIncidentTypesArgs struct {
	Name *string `pulumi:"name"`
	Slug *string `pulumi:"slug"`
}

// A collection of values returned by getIncidentTypes.
type GetIncidentTypesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id            string                         `pulumi:"id"`
	IncidentTypes []GetIncidentTypesIncidentType `pulumi:"incidentTypes"`
	Name          *string                        `pulumi:"name"`
	Slug          *string                        `pulumi:"slug"`
}

func GetIncidentTypesOutput(ctx *pulumi.Context, args GetIncidentTypesOutputArgs, opts ...pulumi.InvokeOption) GetIncidentTypesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetIncidentTypesResultOutput, error) {
			args := v.(GetIncidentTypesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("rootly:index/getIncidentTypes:getIncidentTypes", args, GetIncidentTypesResultOutput{}, options).(GetIncidentTypesResultOutput), nil
		}).(GetIncidentTypesResultOutput)
}

// A collection of arguments for invoking getIncidentTypes.
type GetIncidentTypesOutputArgs struct {
	Name pulumi.StringPtrInput `pulumi:"name"`
	Slug pulumi.StringPtrInput `pulumi:"slug"`
}

func (GetIncidentTypesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIncidentTypesArgs)(nil)).Elem()
}

// A collection of values returned by getIncidentTypes.
type GetIncidentTypesResultOutput struct{ *pulumi.OutputState }

func (GetIncidentTypesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIncidentTypesResult)(nil)).Elem()
}

func (o GetIncidentTypesResultOutput) ToGetIncidentTypesResultOutput() GetIncidentTypesResultOutput {
	return o
}

func (o GetIncidentTypesResultOutput) ToGetIncidentTypesResultOutputWithContext(ctx context.Context) GetIncidentTypesResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetIncidentTypesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIncidentTypesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetIncidentTypesResultOutput) IncidentTypes() GetIncidentTypesIncidentTypeArrayOutput {
	return o.ApplyT(func(v GetIncidentTypesResult) []GetIncidentTypesIncidentType { return v.IncidentTypes }).(GetIncidentTypesIncidentTypeArrayOutput)
}

func (o GetIncidentTypesResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetIncidentTypesResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o GetIncidentTypesResultOutput) Slug() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetIncidentTypesResult) *string { return v.Slug }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIncidentTypesResultOutput{})
}
