// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rootly

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rootlyhq/pulumi-rootly/sdk/v3/go/rootly/internal"
)

// ## Import
//
// OverrideShift can be imported using the `import` command.
//
// ```sh
// $ pulumi import rootly:index/overrideShift:OverrideShift primary a816421c-6ceb-481a-87c4-585e47451f24
// ```
//
// Or using an `import` block.
//
// Locate the resource id in the web app, or retrieve it by listing resources through the API if it's not visible in the web app.
//
// HCL can be generated from the import block using the `-generate-config-out` flag.
//
// ```sh
// pulumi preview -generate-config-out=generated.tf
// ```
type OverrideShift struct {
	pulumi.CustomResourceState

	// End datetime of shift
	EndsAt pulumi.StringOutput `pulumi:"endsAt"`
	// ID of rotation
	RotationId pulumi.StringOutput `pulumi:"rotationId"`
	// ID of schedule
	ScheduleId pulumi.StringOutput `pulumi:"scheduleId"`
	// Start datetime of shift
	StartsAt pulumi.StringOutput `pulumi:"startsAt"`
	// Override shift user
	UserId pulumi.IntOutput `pulumi:"userId"`
}

// NewOverrideShift registers a new resource with the given unique name, arguments, and options.
func NewOverrideShift(ctx *pulumi.Context,
	name string, args *OverrideShiftArgs, opts ...pulumi.ResourceOption) (*OverrideShift, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EndsAt == nil {
		return nil, errors.New("invalid value for required argument 'EndsAt'")
	}
	if args.StartsAt == nil {
		return nil, errors.New("invalid value for required argument 'StartsAt'")
	}
	if args.UserId == nil {
		return nil, errors.New("invalid value for required argument 'UserId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OverrideShift
	err := ctx.RegisterResource("rootly:index/overrideShift:OverrideShift", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOverrideShift gets an existing OverrideShift resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOverrideShift(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OverrideShiftState, opts ...pulumi.ResourceOption) (*OverrideShift, error) {
	var resource OverrideShift
	err := ctx.ReadResource("rootly:index/overrideShift:OverrideShift", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OverrideShift resources.
type overrideShiftState struct {
	// End datetime of shift
	EndsAt *string `pulumi:"endsAt"`
	// ID of rotation
	RotationId *string `pulumi:"rotationId"`
	// ID of schedule
	ScheduleId *string `pulumi:"scheduleId"`
	// Start datetime of shift
	StartsAt *string `pulumi:"startsAt"`
	// Override shift user
	UserId *int `pulumi:"userId"`
}

type OverrideShiftState struct {
	// End datetime of shift
	EndsAt pulumi.StringPtrInput
	// ID of rotation
	RotationId pulumi.StringPtrInput
	// ID of schedule
	ScheduleId pulumi.StringPtrInput
	// Start datetime of shift
	StartsAt pulumi.StringPtrInput
	// Override shift user
	UserId pulumi.IntPtrInput
}

func (OverrideShiftState) ElementType() reflect.Type {
	return reflect.TypeOf((*overrideShiftState)(nil)).Elem()
}

type overrideShiftArgs struct {
	// End datetime of shift
	EndsAt string `pulumi:"endsAt"`
	// ID of rotation
	RotationId *string `pulumi:"rotationId"`
	// ID of schedule
	ScheduleId *string `pulumi:"scheduleId"`
	// Start datetime of shift
	StartsAt string `pulumi:"startsAt"`
	// Override shift user
	UserId int `pulumi:"userId"`
}

// The set of arguments for constructing a OverrideShift resource.
type OverrideShiftArgs struct {
	// End datetime of shift
	EndsAt pulumi.StringInput
	// ID of rotation
	RotationId pulumi.StringPtrInput
	// ID of schedule
	ScheduleId pulumi.StringPtrInput
	// Start datetime of shift
	StartsAt pulumi.StringInput
	// Override shift user
	UserId pulumi.IntInput
}

func (OverrideShiftArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*overrideShiftArgs)(nil)).Elem()
}

type OverrideShiftInput interface {
	pulumi.Input

	ToOverrideShiftOutput() OverrideShiftOutput
	ToOverrideShiftOutputWithContext(ctx context.Context) OverrideShiftOutput
}

func (*OverrideShift) ElementType() reflect.Type {
	return reflect.TypeOf((**OverrideShift)(nil)).Elem()
}

func (i *OverrideShift) ToOverrideShiftOutput() OverrideShiftOutput {
	return i.ToOverrideShiftOutputWithContext(context.Background())
}

func (i *OverrideShift) ToOverrideShiftOutputWithContext(ctx context.Context) OverrideShiftOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OverrideShiftOutput)
}

// OverrideShiftArrayInput is an input type that accepts OverrideShiftArray and OverrideShiftArrayOutput values.
// You can construct a concrete instance of `OverrideShiftArrayInput` via:
//
//	OverrideShiftArray{ OverrideShiftArgs{...} }
type OverrideShiftArrayInput interface {
	pulumi.Input

	ToOverrideShiftArrayOutput() OverrideShiftArrayOutput
	ToOverrideShiftArrayOutputWithContext(context.Context) OverrideShiftArrayOutput
}

type OverrideShiftArray []OverrideShiftInput

func (OverrideShiftArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OverrideShift)(nil)).Elem()
}

func (i OverrideShiftArray) ToOverrideShiftArrayOutput() OverrideShiftArrayOutput {
	return i.ToOverrideShiftArrayOutputWithContext(context.Background())
}

func (i OverrideShiftArray) ToOverrideShiftArrayOutputWithContext(ctx context.Context) OverrideShiftArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OverrideShiftArrayOutput)
}

// OverrideShiftMapInput is an input type that accepts OverrideShiftMap and OverrideShiftMapOutput values.
// You can construct a concrete instance of `OverrideShiftMapInput` via:
//
//	OverrideShiftMap{ "key": OverrideShiftArgs{...} }
type OverrideShiftMapInput interface {
	pulumi.Input

	ToOverrideShiftMapOutput() OverrideShiftMapOutput
	ToOverrideShiftMapOutputWithContext(context.Context) OverrideShiftMapOutput
}

type OverrideShiftMap map[string]OverrideShiftInput

func (OverrideShiftMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OverrideShift)(nil)).Elem()
}

func (i OverrideShiftMap) ToOverrideShiftMapOutput() OverrideShiftMapOutput {
	return i.ToOverrideShiftMapOutputWithContext(context.Background())
}

func (i OverrideShiftMap) ToOverrideShiftMapOutputWithContext(ctx context.Context) OverrideShiftMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OverrideShiftMapOutput)
}

type OverrideShiftOutput struct{ *pulumi.OutputState }

func (OverrideShiftOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OverrideShift)(nil)).Elem()
}

func (o OverrideShiftOutput) ToOverrideShiftOutput() OverrideShiftOutput {
	return o
}

func (o OverrideShiftOutput) ToOverrideShiftOutputWithContext(ctx context.Context) OverrideShiftOutput {
	return o
}

// End datetime of shift
func (o OverrideShiftOutput) EndsAt() pulumi.StringOutput {
	return o.ApplyT(func(v *OverrideShift) pulumi.StringOutput { return v.EndsAt }).(pulumi.StringOutput)
}

// ID of rotation
func (o OverrideShiftOutput) RotationId() pulumi.StringOutput {
	return o.ApplyT(func(v *OverrideShift) pulumi.StringOutput { return v.RotationId }).(pulumi.StringOutput)
}

// ID of schedule
func (o OverrideShiftOutput) ScheduleId() pulumi.StringOutput {
	return o.ApplyT(func(v *OverrideShift) pulumi.StringOutput { return v.ScheduleId }).(pulumi.StringOutput)
}

// Start datetime of shift
func (o OverrideShiftOutput) StartsAt() pulumi.StringOutput {
	return o.ApplyT(func(v *OverrideShift) pulumi.StringOutput { return v.StartsAt }).(pulumi.StringOutput)
}

// Override shift user
func (o OverrideShiftOutput) UserId() pulumi.IntOutput {
	return o.ApplyT(func(v *OverrideShift) pulumi.IntOutput { return v.UserId }).(pulumi.IntOutput)
}

type OverrideShiftArrayOutput struct{ *pulumi.OutputState }

func (OverrideShiftArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OverrideShift)(nil)).Elem()
}

func (o OverrideShiftArrayOutput) ToOverrideShiftArrayOutput() OverrideShiftArrayOutput {
	return o
}

func (o OverrideShiftArrayOutput) ToOverrideShiftArrayOutputWithContext(ctx context.Context) OverrideShiftArrayOutput {
	return o
}

func (o OverrideShiftArrayOutput) Index(i pulumi.IntInput) OverrideShiftOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *OverrideShift {
		return vs[0].([]*OverrideShift)[vs[1].(int)]
	}).(OverrideShiftOutput)
}

type OverrideShiftMapOutput struct{ *pulumi.OutputState }

func (OverrideShiftMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OverrideShift)(nil)).Elem()
}

func (o OverrideShiftMapOutput) ToOverrideShiftMapOutput() OverrideShiftMapOutput {
	return o
}

func (o OverrideShiftMapOutput) ToOverrideShiftMapOutputWithContext(ctx context.Context) OverrideShiftMapOutput {
	return o
}

func (o OverrideShiftMapOutput) MapIndex(k pulumi.StringInput) OverrideShiftOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *OverrideShift {
		return vs[0].(map[string]*OverrideShift)[vs[1].(string)]
	}).(OverrideShiftOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OverrideShiftInput)(nil)).Elem(), &OverrideShift{})
	pulumi.RegisterInputType(reflect.TypeOf((*OverrideShiftArrayInput)(nil)).Elem(), OverrideShiftArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OverrideShiftMapInput)(nil)).Elem(), OverrideShiftMap{})
	pulumi.RegisterOutputType(OverrideShiftOutput{})
	pulumi.RegisterOutputType(OverrideShiftArrayOutput{})
	pulumi.RegisterOutputType(OverrideShiftMapOutput{})
}
