// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rootly

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rootlyhq/pulumi-rootly/sdk/v3/go/rootly/internal"
)

// Manages workflow archiveMicrosoftTeamsChannels task.
//
// ## Import
//
// Using `pulumi import`, import WorkflowTaskArchiveMicrosoftTeamsChannels using the `id`. For example:
//
// ```sh
// $ pulumi import rootly:index/workflowTaskArchiveMicrosoftTeamsChannels:WorkflowTaskArchiveMicrosoftTeamsChannels my-resource 00000000-0000-0000-0000-000000000000
// ```
type WorkflowTaskArchiveMicrosoftTeamsChannels struct {
	pulumi.CustomResourceState

	// Enable/disable this workflow task
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// Name of the workflow task
	Name pulumi.StringOutput `pulumi:"name"`
	// The position of the workflow task (1 being top of list)
	Position pulumi.IntOutput `pulumi:"position"`
	// Skip workflow task if any failures
	SkipOnFailure pulumi.BoolPtrOutput `pulumi:"skipOnFailure"`
	// The parameters for this workflow task.
	TaskParams WorkflowTaskArchiveMicrosoftTeamsChannelsTaskParamsOutput `pulumi:"taskParams"`
	// The ID of the parent workflow
	WorkflowId pulumi.StringOutput `pulumi:"workflowId"`
}

// NewWorkflowTaskArchiveMicrosoftTeamsChannels registers a new resource with the given unique name, arguments, and options.
func NewWorkflowTaskArchiveMicrosoftTeamsChannels(ctx *pulumi.Context,
	name string, args *WorkflowTaskArchiveMicrosoftTeamsChannelsArgs, opts ...pulumi.ResourceOption) (*WorkflowTaskArchiveMicrosoftTeamsChannels, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.TaskParams == nil {
		return nil, errors.New("invalid value for required argument 'TaskParams'")
	}
	if args.WorkflowId == nil {
		return nil, errors.New("invalid value for required argument 'WorkflowId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WorkflowTaskArchiveMicrosoftTeamsChannels
	err := ctx.RegisterResource("rootly:index/workflowTaskArchiveMicrosoftTeamsChannels:WorkflowTaskArchiveMicrosoftTeamsChannels", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkflowTaskArchiveMicrosoftTeamsChannels gets an existing WorkflowTaskArchiveMicrosoftTeamsChannels resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkflowTaskArchiveMicrosoftTeamsChannels(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkflowTaskArchiveMicrosoftTeamsChannelsState, opts ...pulumi.ResourceOption) (*WorkflowTaskArchiveMicrosoftTeamsChannels, error) {
	var resource WorkflowTaskArchiveMicrosoftTeamsChannels
	err := ctx.ReadResource("rootly:index/workflowTaskArchiveMicrosoftTeamsChannels:WorkflowTaskArchiveMicrosoftTeamsChannels", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkflowTaskArchiveMicrosoftTeamsChannels resources.
type workflowTaskArchiveMicrosoftTeamsChannelsState struct {
	// Enable/disable this workflow task
	Enabled *bool `pulumi:"enabled"`
	// Name of the workflow task
	Name *string `pulumi:"name"`
	// The position of the workflow task (1 being top of list)
	Position *int `pulumi:"position"`
	// Skip workflow task if any failures
	SkipOnFailure *bool `pulumi:"skipOnFailure"`
	// The parameters for this workflow task.
	TaskParams *WorkflowTaskArchiveMicrosoftTeamsChannelsTaskParams `pulumi:"taskParams"`
	// The ID of the parent workflow
	WorkflowId *string `pulumi:"workflowId"`
}

type WorkflowTaskArchiveMicrosoftTeamsChannelsState struct {
	// Enable/disable this workflow task
	Enabled pulumi.BoolPtrInput
	// Name of the workflow task
	Name pulumi.StringPtrInput
	// The position of the workflow task (1 being top of list)
	Position pulumi.IntPtrInput
	// Skip workflow task if any failures
	SkipOnFailure pulumi.BoolPtrInput
	// The parameters for this workflow task.
	TaskParams WorkflowTaskArchiveMicrosoftTeamsChannelsTaskParamsPtrInput
	// The ID of the parent workflow
	WorkflowId pulumi.StringPtrInput
}

func (WorkflowTaskArchiveMicrosoftTeamsChannelsState) ElementType() reflect.Type {
	return reflect.TypeOf((*workflowTaskArchiveMicrosoftTeamsChannelsState)(nil)).Elem()
}

type workflowTaskArchiveMicrosoftTeamsChannelsArgs struct {
	// Enable/disable this workflow task
	Enabled *bool `pulumi:"enabled"`
	// Name of the workflow task
	Name *string `pulumi:"name"`
	// The position of the workflow task (1 being top of list)
	Position *int `pulumi:"position"`
	// Skip workflow task if any failures
	SkipOnFailure *bool `pulumi:"skipOnFailure"`
	// The parameters for this workflow task.
	TaskParams WorkflowTaskArchiveMicrosoftTeamsChannelsTaskParams `pulumi:"taskParams"`
	// The ID of the parent workflow
	WorkflowId string `pulumi:"workflowId"`
}

// The set of arguments for constructing a WorkflowTaskArchiveMicrosoftTeamsChannels resource.
type WorkflowTaskArchiveMicrosoftTeamsChannelsArgs struct {
	// Enable/disable this workflow task
	Enabled pulumi.BoolPtrInput
	// Name of the workflow task
	Name pulumi.StringPtrInput
	// The position of the workflow task (1 being top of list)
	Position pulumi.IntPtrInput
	// Skip workflow task if any failures
	SkipOnFailure pulumi.BoolPtrInput
	// The parameters for this workflow task.
	TaskParams WorkflowTaskArchiveMicrosoftTeamsChannelsTaskParamsInput
	// The ID of the parent workflow
	WorkflowId pulumi.StringInput
}

func (WorkflowTaskArchiveMicrosoftTeamsChannelsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*workflowTaskArchiveMicrosoftTeamsChannelsArgs)(nil)).Elem()
}

type WorkflowTaskArchiveMicrosoftTeamsChannelsInput interface {
	pulumi.Input

	ToWorkflowTaskArchiveMicrosoftTeamsChannelsOutput() WorkflowTaskArchiveMicrosoftTeamsChannelsOutput
	ToWorkflowTaskArchiveMicrosoftTeamsChannelsOutputWithContext(ctx context.Context) WorkflowTaskArchiveMicrosoftTeamsChannelsOutput
}

func (*WorkflowTaskArchiveMicrosoftTeamsChannels) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkflowTaskArchiveMicrosoftTeamsChannels)(nil)).Elem()
}

func (i *WorkflowTaskArchiveMicrosoftTeamsChannels) ToWorkflowTaskArchiveMicrosoftTeamsChannelsOutput() WorkflowTaskArchiveMicrosoftTeamsChannelsOutput {
	return i.ToWorkflowTaskArchiveMicrosoftTeamsChannelsOutputWithContext(context.Background())
}

func (i *WorkflowTaskArchiveMicrosoftTeamsChannels) ToWorkflowTaskArchiveMicrosoftTeamsChannelsOutputWithContext(ctx context.Context) WorkflowTaskArchiveMicrosoftTeamsChannelsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkflowTaskArchiveMicrosoftTeamsChannelsOutput)
}

// WorkflowTaskArchiveMicrosoftTeamsChannelsArrayInput is an input type that accepts WorkflowTaskArchiveMicrosoftTeamsChannelsArray and WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput values.
// You can construct a concrete instance of `WorkflowTaskArchiveMicrosoftTeamsChannelsArrayInput` via:
//
//	WorkflowTaskArchiveMicrosoftTeamsChannelsArray{ WorkflowTaskArchiveMicrosoftTeamsChannelsArgs{...} }
type WorkflowTaskArchiveMicrosoftTeamsChannelsArrayInput interface {
	pulumi.Input

	ToWorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput() WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput
	ToWorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutputWithContext(context.Context) WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput
}

type WorkflowTaskArchiveMicrosoftTeamsChannelsArray []WorkflowTaskArchiveMicrosoftTeamsChannelsInput

func (WorkflowTaskArchiveMicrosoftTeamsChannelsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkflowTaskArchiveMicrosoftTeamsChannels)(nil)).Elem()
}

func (i WorkflowTaskArchiveMicrosoftTeamsChannelsArray) ToWorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput() WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput {
	return i.ToWorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutputWithContext(context.Background())
}

func (i WorkflowTaskArchiveMicrosoftTeamsChannelsArray) ToWorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutputWithContext(ctx context.Context) WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput)
}

// WorkflowTaskArchiveMicrosoftTeamsChannelsMapInput is an input type that accepts WorkflowTaskArchiveMicrosoftTeamsChannelsMap and WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput values.
// You can construct a concrete instance of `WorkflowTaskArchiveMicrosoftTeamsChannelsMapInput` via:
//
//	WorkflowTaskArchiveMicrosoftTeamsChannelsMap{ "key": WorkflowTaskArchiveMicrosoftTeamsChannelsArgs{...} }
type WorkflowTaskArchiveMicrosoftTeamsChannelsMapInput interface {
	pulumi.Input

	ToWorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput() WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput
	ToWorkflowTaskArchiveMicrosoftTeamsChannelsMapOutputWithContext(context.Context) WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput
}

type WorkflowTaskArchiveMicrosoftTeamsChannelsMap map[string]WorkflowTaskArchiveMicrosoftTeamsChannelsInput

func (WorkflowTaskArchiveMicrosoftTeamsChannelsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkflowTaskArchiveMicrosoftTeamsChannels)(nil)).Elem()
}

func (i WorkflowTaskArchiveMicrosoftTeamsChannelsMap) ToWorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput() WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput {
	return i.ToWorkflowTaskArchiveMicrosoftTeamsChannelsMapOutputWithContext(context.Background())
}

func (i WorkflowTaskArchiveMicrosoftTeamsChannelsMap) ToWorkflowTaskArchiveMicrosoftTeamsChannelsMapOutputWithContext(ctx context.Context) WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput)
}

type WorkflowTaskArchiveMicrosoftTeamsChannelsOutput struct{ *pulumi.OutputState }

func (WorkflowTaskArchiveMicrosoftTeamsChannelsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkflowTaskArchiveMicrosoftTeamsChannels)(nil)).Elem()
}

func (o WorkflowTaskArchiveMicrosoftTeamsChannelsOutput) ToWorkflowTaskArchiveMicrosoftTeamsChannelsOutput() WorkflowTaskArchiveMicrosoftTeamsChannelsOutput {
	return o
}

func (o WorkflowTaskArchiveMicrosoftTeamsChannelsOutput) ToWorkflowTaskArchiveMicrosoftTeamsChannelsOutputWithContext(ctx context.Context) WorkflowTaskArchiveMicrosoftTeamsChannelsOutput {
	return o
}

// Enable/disable this workflow task
func (o WorkflowTaskArchiveMicrosoftTeamsChannelsOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkflowTaskArchiveMicrosoftTeamsChannels) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Name of the workflow task
func (o WorkflowTaskArchiveMicrosoftTeamsChannelsOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkflowTaskArchiveMicrosoftTeamsChannels) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The position of the workflow task (1 being top of list)
func (o WorkflowTaskArchiveMicrosoftTeamsChannelsOutput) Position() pulumi.IntOutput {
	return o.ApplyT(func(v *WorkflowTaskArchiveMicrosoftTeamsChannels) pulumi.IntOutput { return v.Position }).(pulumi.IntOutput)
}

// Skip workflow task if any failures
func (o WorkflowTaskArchiveMicrosoftTeamsChannelsOutput) SkipOnFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkflowTaskArchiveMicrosoftTeamsChannels) pulumi.BoolPtrOutput { return v.SkipOnFailure }).(pulumi.BoolPtrOutput)
}

// The parameters for this workflow task.
func (o WorkflowTaskArchiveMicrosoftTeamsChannelsOutput) TaskParams() WorkflowTaskArchiveMicrosoftTeamsChannelsTaskParamsOutput {
	return o.ApplyT(func(v *WorkflowTaskArchiveMicrosoftTeamsChannels) WorkflowTaskArchiveMicrosoftTeamsChannelsTaskParamsOutput {
		return v.TaskParams
	}).(WorkflowTaskArchiveMicrosoftTeamsChannelsTaskParamsOutput)
}

// The ID of the parent workflow
func (o WorkflowTaskArchiveMicrosoftTeamsChannelsOutput) WorkflowId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkflowTaskArchiveMicrosoftTeamsChannels) pulumi.StringOutput { return v.WorkflowId }).(pulumi.StringOutput)
}

type WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput struct{ *pulumi.OutputState }

func (WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkflowTaskArchiveMicrosoftTeamsChannels)(nil)).Elem()
}

func (o WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput) ToWorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput() WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput {
	return o
}

func (o WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput) ToWorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutputWithContext(ctx context.Context) WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput {
	return o
}

func (o WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput) Index(i pulumi.IntInput) WorkflowTaskArchiveMicrosoftTeamsChannelsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WorkflowTaskArchiveMicrosoftTeamsChannels {
		return vs[0].([]*WorkflowTaskArchiveMicrosoftTeamsChannels)[vs[1].(int)]
	}).(WorkflowTaskArchiveMicrosoftTeamsChannelsOutput)
}

type WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput struct{ *pulumi.OutputState }

func (WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkflowTaskArchiveMicrosoftTeamsChannels)(nil)).Elem()
}

func (o WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput) ToWorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput() WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput {
	return o
}

func (o WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput) ToWorkflowTaskArchiveMicrosoftTeamsChannelsMapOutputWithContext(ctx context.Context) WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput {
	return o
}

func (o WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput) MapIndex(k pulumi.StringInput) WorkflowTaskArchiveMicrosoftTeamsChannelsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WorkflowTaskArchiveMicrosoftTeamsChannels {
		return vs[0].(map[string]*WorkflowTaskArchiveMicrosoftTeamsChannels)[vs[1].(string)]
	}).(WorkflowTaskArchiveMicrosoftTeamsChannelsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkflowTaskArchiveMicrosoftTeamsChannelsInput)(nil)).Elem(), &WorkflowTaskArchiveMicrosoftTeamsChannels{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkflowTaskArchiveMicrosoftTeamsChannelsArrayInput)(nil)).Elem(), WorkflowTaskArchiveMicrosoftTeamsChannelsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkflowTaskArchiveMicrosoftTeamsChannelsMapInput)(nil)).Elem(), WorkflowTaskArchiveMicrosoftTeamsChannelsMap{})
	pulumi.RegisterOutputType(WorkflowTaskArchiveMicrosoftTeamsChannelsOutput{})
	pulumi.RegisterOutputType(WorkflowTaskArchiveMicrosoftTeamsChannelsArrayOutput{})
	pulumi.RegisterOutputType(WorkflowTaskArchiveMicrosoftTeamsChannelsMapOutput{})
}
