// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rootly

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rootlyhq/pulumi-rootly/sdk/v3/go/rootly/internal"
)

// ## Import
//
// WorkflowActionItemFormFieldCondition can be imported using the `import` command.
//
// ```sh
// $ pulumi import rootly:index/workflowActionItemFormFieldCondition:WorkflowActionItemFormFieldCondition primary a816421c-6ceb-481a-87c4-585e47451f24
// ```
//
// Or using an `import` block.
//
// Locate the resource id in the web app, or retrieve it by listing resources through the API if it's not visible in the web app.
//
// HCL can be generated from the import block using the `-generate-config-out` flag.
//
// ```sh
// pulumi preview -generate-config-out=generated.tf
// ```
type WorkflowActionItemFormFieldCondition struct {
	pulumi.CustomResourceState

	// The trigger condition. Value must be one of `IS`, `IS NOT`, `ANY`, `CONTAINS`, `CONTAINS_ALL`, `CONTAINS_NONE`, `NONE`, `SET`, `UNSET`.
	ActionItemCondition pulumi.StringPtrOutput `pulumi:"actionItemCondition"`
	// The custom field for this condition
	FormFieldId              pulumi.StringOutput      `pulumi:"formFieldId"`
	SelectedCatalogEntityIds pulumi.StringArrayOutput `pulumi:"selectedCatalogEntityIds"`
	SelectedCauseIds         pulumi.StringArrayOutput `pulumi:"selectedCauseIds"`
	SelectedEnvironmentIds   pulumi.StringArrayOutput `pulumi:"selectedEnvironmentIds"`
	SelectedFunctionalityIds pulumi.StringArrayOutput `pulumi:"selectedFunctionalityIds"`
	SelectedGroupIds         pulumi.StringArrayOutput `pulumi:"selectedGroupIds"`
	SelectedIncidentTypeIds  pulumi.StringArrayOutput `pulumi:"selectedIncidentTypeIds"`
	SelectedOptionIds        pulumi.StringArrayOutput `pulumi:"selectedOptionIds"`
	SelectedServiceIds       pulumi.StringArrayOutput `pulumi:"selectedServiceIds"`
	SelectedUserIds          pulumi.IntArrayOutput    `pulumi:"selectedUserIds"`
	Values                   pulumi.StringArrayOutput `pulumi:"values"`
	// The workflow for this condition
	WorkflowId pulumi.StringOutput `pulumi:"workflowId"`
}

// NewWorkflowActionItemFormFieldCondition registers a new resource with the given unique name, arguments, and options.
func NewWorkflowActionItemFormFieldCondition(ctx *pulumi.Context,
	name string, args *WorkflowActionItemFormFieldConditionArgs, opts ...pulumi.ResourceOption) (*WorkflowActionItemFormFieldCondition, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.FormFieldId == nil {
		return nil, errors.New("invalid value for required argument 'FormFieldId'")
	}
	if args.WorkflowId == nil {
		return nil, errors.New("invalid value for required argument 'WorkflowId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WorkflowActionItemFormFieldCondition
	err := ctx.RegisterResource("rootly:index/workflowActionItemFormFieldCondition:WorkflowActionItemFormFieldCondition", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkflowActionItemFormFieldCondition gets an existing WorkflowActionItemFormFieldCondition resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkflowActionItemFormFieldCondition(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkflowActionItemFormFieldConditionState, opts ...pulumi.ResourceOption) (*WorkflowActionItemFormFieldCondition, error) {
	var resource WorkflowActionItemFormFieldCondition
	err := ctx.ReadResource("rootly:index/workflowActionItemFormFieldCondition:WorkflowActionItemFormFieldCondition", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkflowActionItemFormFieldCondition resources.
type workflowActionItemFormFieldConditionState struct {
	// The trigger condition. Value must be one of `IS`, `IS NOT`, `ANY`, `CONTAINS`, `CONTAINS_ALL`, `CONTAINS_NONE`, `NONE`, `SET`, `UNSET`.
	ActionItemCondition *string `pulumi:"actionItemCondition"`
	// The custom field for this condition
	FormFieldId              *string  `pulumi:"formFieldId"`
	SelectedCatalogEntityIds []string `pulumi:"selectedCatalogEntityIds"`
	SelectedCauseIds         []string `pulumi:"selectedCauseIds"`
	SelectedEnvironmentIds   []string `pulumi:"selectedEnvironmentIds"`
	SelectedFunctionalityIds []string `pulumi:"selectedFunctionalityIds"`
	SelectedGroupIds         []string `pulumi:"selectedGroupIds"`
	SelectedIncidentTypeIds  []string `pulumi:"selectedIncidentTypeIds"`
	SelectedOptionIds        []string `pulumi:"selectedOptionIds"`
	SelectedServiceIds       []string `pulumi:"selectedServiceIds"`
	SelectedUserIds          []int    `pulumi:"selectedUserIds"`
	Values                   []string `pulumi:"values"`
	// The workflow for this condition
	WorkflowId *string `pulumi:"workflowId"`
}

type WorkflowActionItemFormFieldConditionState struct {
	// The trigger condition. Value must be one of `IS`, `IS NOT`, `ANY`, `CONTAINS`, `CONTAINS_ALL`, `CONTAINS_NONE`, `NONE`, `SET`, `UNSET`.
	ActionItemCondition pulumi.StringPtrInput
	// The custom field for this condition
	FormFieldId              pulumi.StringPtrInput
	SelectedCatalogEntityIds pulumi.StringArrayInput
	SelectedCauseIds         pulumi.StringArrayInput
	SelectedEnvironmentIds   pulumi.StringArrayInput
	SelectedFunctionalityIds pulumi.StringArrayInput
	SelectedGroupIds         pulumi.StringArrayInput
	SelectedIncidentTypeIds  pulumi.StringArrayInput
	SelectedOptionIds        pulumi.StringArrayInput
	SelectedServiceIds       pulumi.StringArrayInput
	SelectedUserIds          pulumi.IntArrayInput
	Values                   pulumi.StringArrayInput
	// The workflow for this condition
	WorkflowId pulumi.StringPtrInput
}

func (WorkflowActionItemFormFieldConditionState) ElementType() reflect.Type {
	return reflect.TypeOf((*workflowActionItemFormFieldConditionState)(nil)).Elem()
}

type workflowActionItemFormFieldConditionArgs struct {
	// The trigger condition. Value must be one of `IS`, `IS NOT`, `ANY`, `CONTAINS`, `CONTAINS_ALL`, `CONTAINS_NONE`, `NONE`, `SET`, `UNSET`.
	ActionItemCondition *string `pulumi:"actionItemCondition"`
	// The custom field for this condition
	FormFieldId              string   `pulumi:"formFieldId"`
	SelectedCatalogEntityIds []string `pulumi:"selectedCatalogEntityIds"`
	SelectedCauseIds         []string `pulumi:"selectedCauseIds"`
	SelectedEnvironmentIds   []string `pulumi:"selectedEnvironmentIds"`
	SelectedFunctionalityIds []string `pulumi:"selectedFunctionalityIds"`
	SelectedGroupIds         []string `pulumi:"selectedGroupIds"`
	SelectedIncidentTypeIds  []string `pulumi:"selectedIncidentTypeIds"`
	SelectedOptionIds        []string `pulumi:"selectedOptionIds"`
	SelectedServiceIds       []string `pulumi:"selectedServiceIds"`
	SelectedUserIds          []int    `pulumi:"selectedUserIds"`
	Values                   []string `pulumi:"values"`
	// The workflow for this condition
	WorkflowId string `pulumi:"workflowId"`
}

// The set of arguments for constructing a WorkflowActionItemFormFieldCondition resource.
type WorkflowActionItemFormFieldConditionArgs struct {
	// The trigger condition. Value must be one of `IS`, `IS NOT`, `ANY`, `CONTAINS`, `CONTAINS_ALL`, `CONTAINS_NONE`, `NONE`, `SET`, `UNSET`.
	ActionItemCondition pulumi.StringPtrInput
	// The custom field for this condition
	FormFieldId              pulumi.StringInput
	SelectedCatalogEntityIds pulumi.StringArrayInput
	SelectedCauseIds         pulumi.StringArrayInput
	SelectedEnvironmentIds   pulumi.StringArrayInput
	SelectedFunctionalityIds pulumi.StringArrayInput
	SelectedGroupIds         pulumi.StringArrayInput
	SelectedIncidentTypeIds  pulumi.StringArrayInput
	SelectedOptionIds        pulumi.StringArrayInput
	SelectedServiceIds       pulumi.StringArrayInput
	SelectedUserIds          pulumi.IntArrayInput
	Values                   pulumi.StringArrayInput
	// The workflow for this condition
	WorkflowId pulumi.StringInput
}

func (WorkflowActionItemFormFieldConditionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*workflowActionItemFormFieldConditionArgs)(nil)).Elem()
}

type WorkflowActionItemFormFieldConditionInput interface {
	pulumi.Input

	ToWorkflowActionItemFormFieldConditionOutput() WorkflowActionItemFormFieldConditionOutput
	ToWorkflowActionItemFormFieldConditionOutputWithContext(ctx context.Context) WorkflowActionItemFormFieldConditionOutput
}

func (*WorkflowActionItemFormFieldCondition) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkflowActionItemFormFieldCondition)(nil)).Elem()
}

func (i *WorkflowActionItemFormFieldCondition) ToWorkflowActionItemFormFieldConditionOutput() WorkflowActionItemFormFieldConditionOutput {
	return i.ToWorkflowActionItemFormFieldConditionOutputWithContext(context.Background())
}

func (i *WorkflowActionItemFormFieldCondition) ToWorkflowActionItemFormFieldConditionOutputWithContext(ctx context.Context) WorkflowActionItemFormFieldConditionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkflowActionItemFormFieldConditionOutput)
}

// WorkflowActionItemFormFieldConditionArrayInput is an input type that accepts WorkflowActionItemFormFieldConditionArray and WorkflowActionItemFormFieldConditionArrayOutput values.
// You can construct a concrete instance of `WorkflowActionItemFormFieldConditionArrayInput` via:
//
//	WorkflowActionItemFormFieldConditionArray{ WorkflowActionItemFormFieldConditionArgs{...} }
type WorkflowActionItemFormFieldConditionArrayInput interface {
	pulumi.Input

	ToWorkflowActionItemFormFieldConditionArrayOutput() WorkflowActionItemFormFieldConditionArrayOutput
	ToWorkflowActionItemFormFieldConditionArrayOutputWithContext(context.Context) WorkflowActionItemFormFieldConditionArrayOutput
}

type WorkflowActionItemFormFieldConditionArray []WorkflowActionItemFormFieldConditionInput

func (WorkflowActionItemFormFieldConditionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkflowActionItemFormFieldCondition)(nil)).Elem()
}

func (i WorkflowActionItemFormFieldConditionArray) ToWorkflowActionItemFormFieldConditionArrayOutput() WorkflowActionItemFormFieldConditionArrayOutput {
	return i.ToWorkflowActionItemFormFieldConditionArrayOutputWithContext(context.Background())
}

func (i WorkflowActionItemFormFieldConditionArray) ToWorkflowActionItemFormFieldConditionArrayOutputWithContext(ctx context.Context) WorkflowActionItemFormFieldConditionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkflowActionItemFormFieldConditionArrayOutput)
}

// WorkflowActionItemFormFieldConditionMapInput is an input type that accepts WorkflowActionItemFormFieldConditionMap and WorkflowActionItemFormFieldConditionMapOutput values.
// You can construct a concrete instance of `WorkflowActionItemFormFieldConditionMapInput` via:
//
//	WorkflowActionItemFormFieldConditionMap{ "key": WorkflowActionItemFormFieldConditionArgs{...} }
type WorkflowActionItemFormFieldConditionMapInput interface {
	pulumi.Input

	ToWorkflowActionItemFormFieldConditionMapOutput() WorkflowActionItemFormFieldConditionMapOutput
	ToWorkflowActionItemFormFieldConditionMapOutputWithContext(context.Context) WorkflowActionItemFormFieldConditionMapOutput
}

type WorkflowActionItemFormFieldConditionMap map[string]WorkflowActionItemFormFieldConditionInput

func (WorkflowActionItemFormFieldConditionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkflowActionItemFormFieldCondition)(nil)).Elem()
}

func (i WorkflowActionItemFormFieldConditionMap) ToWorkflowActionItemFormFieldConditionMapOutput() WorkflowActionItemFormFieldConditionMapOutput {
	return i.ToWorkflowActionItemFormFieldConditionMapOutputWithContext(context.Background())
}

func (i WorkflowActionItemFormFieldConditionMap) ToWorkflowActionItemFormFieldConditionMapOutputWithContext(ctx context.Context) WorkflowActionItemFormFieldConditionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkflowActionItemFormFieldConditionMapOutput)
}

type WorkflowActionItemFormFieldConditionOutput struct{ *pulumi.OutputState }

func (WorkflowActionItemFormFieldConditionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkflowActionItemFormFieldCondition)(nil)).Elem()
}

func (o WorkflowActionItemFormFieldConditionOutput) ToWorkflowActionItemFormFieldConditionOutput() WorkflowActionItemFormFieldConditionOutput {
	return o
}

func (o WorkflowActionItemFormFieldConditionOutput) ToWorkflowActionItemFormFieldConditionOutputWithContext(ctx context.Context) WorkflowActionItemFormFieldConditionOutput {
	return o
}

// The trigger condition. Value must be one of `IS`, `IS NOT`, `ANY`, `CONTAINS`, `CONTAINS_ALL`, `CONTAINS_NONE`, `NONE`, `SET`, `UNSET`.
func (o WorkflowActionItemFormFieldConditionOutput) ActionItemCondition() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringPtrOutput { return v.ActionItemCondition }).(pulumi.StringPtrOutput)
}

// The custom field for this condition
func (o WorkflowActionItemFormFieldConditionOutput) FormFieldId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringOutput { return v.FormFieldId }).(pulumi.StringOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) SelectedCatalogEntityIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringArrayOutput {
		return v.SelectedCatalogEntityIds
	}).(pulumi.StringArrayOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) SelectedCauseIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringArrayOutput { return v.SelectedCauseIds }).(pulumi.StringArrayOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) SelectedEnvironmentIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringArrayOutput {
		return v.SelectedEnvironmentIds
	}).(pulumi.StringArrayOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) SelectedFunctionalityIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringArrayOutput {
		return v.SelectedFunctionalityIds
	}).(pulumi.StringArrayOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) SelectedGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringArrayOutput { return v.SelectedGroupIds }).(pulumi.StringArrayOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) SelectedIncidentTypeIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringArrayOutput {
		return v.SelectedIncidentTypeIds
	}).(pulumi.StringArrayOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) SelectedOptionIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringArrayOutput { return v.SelectedOptionIds }).(pulumi.StringArrayOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) SelectedServiceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringArrayOutput { return v.SelectedServiceIds }).(pulumi.StringArrayOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) SelectedUserIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.IntArrayOutput { return v.SelectedUserIds }).(pulumi.IntArrayOutput)
}

func (o WorkflowActionItemFormFieldConditionOutput) Values() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringArrayOutput { return v.Values }).(pulumi.StringArrayOutput)
}

// The workflow for this condition
func (o WorkflowActionItemFormFieldConditionOutput) WorkflowId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkflowActionItemFormFieldCondition) pulumi.StringOutput { return v.WorkflowId }).(pulumi.StringOutput)
}

type WorkflowActionItemFormFieldConditionArrayOutput struct{ *pulumi.OutputState }

func (WorkflowActionItemFormFieldConditionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkflowActionItemFormFieldCondition)(nil)).Elem()
}

func (o WorkflowActionItemFormFieldConditionArrayOutput) ToWorkflowActionItemFormFieldConditionArrayOutput() WorkflowActionItemFormFieldConditionArrayOutput {
	return o
}

func (o WorkflowActionItemFormFieldConditionArrayOutput) ToWorkflowActionItemFormFieldConditionArrayOutputWithContext(ctx context.Context) WorkflowActionItemFormFieldConditionArrayOutput {
	return o
}

func (o WorkflowActionItemFormFieldConditionArrayOutput) Index(i pulumi.IntInput) WorkflowActionItemFormFieldConditionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WorkflowActionItemFormFieldCondition {
		return vs[0].([]*WorkflowActionItemFormFieldCondition)[vs[1].(int)]
	}).(WorkflowActionItemFormFieldConditionOutput)
}

type WorkflowActionItemFormFieldConditionMapOutput struct{ *pulumi.OutputState }

func (WorkflowActionItemFormFieldConditionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkflowActionItemFormFieldCondition)(nil)).Elem()
}

func (o WorkflowActionItemFormFieldConditionMapOutput) ToWorkflowActionItemFormFieldConditionMapOutput() WorkflowActionItemFormFieldConditionMapOutput {
	return o
}

func (o WorkflowActionItemFormFieldConditionMapOutput) ToWorkflowActionItemFormFieldConditionMapOutputWithContext(ctx context.Context) WorkflowActionItemFormFieldConditionMapOutput {
	return o
}

func (o WorkflowActionItemFormFieldConditionMapOutput) MapIndex(k pulumi.StringInput) WorkflowActionItemFormFieldConditionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WorkflowActionItemFormFieldCondition {
		return vs[0].(map[string]*WorkflowActionItemFormFieldCondition)[vs[1].(string)]
	}).(WorkflowActionItemFormFieldConditionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkflowActionItemFormFieldConditionInput)(nil)).Elem(), &WorkflowActionItemFormFieldCondition{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkflowActionItemFormFieldConditionArrayInput)(nil)).Elem(), WorkflowActionItemFormFieldConditionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkflowActionItemFormFieldConditionMapInput)(nil)).Elem(), WorkflowActionItemFormFieldConditionMap{})
	pulumi.RegisterOutputType(WorkflowActionItemFormFieldConditionOutput{})
	pulumi.RegisterOutputType(WorkflowActionItemFormFieldConditionArrayOutput{})
	pulumi.RegisterOutputType(WorkflowActionItemFormFieldConditionMapOutput{})
}
