# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetCustomFieldOptionResult',
    'AwaitableGetCustomFieldOptionResult',
    'get_custom_field_option',
    'get_custom_field_option_output',
]

@pulumi.output_type
class GetCustomFieldOptionResult:
    """
    A collection of values returned by getCustomFieldOption.
    """
    def __init__(__self__, color=None, id=None, value=None):
        if color and not isinstance(color, str):
            raise TypeError("Expected argument 'color' to be a str")
        pulumi.set(__self__, "color", color)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if value and not isinstance(value, str):
            raise TypeError("Expected argument 'value' to be a str")
        pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def color(self) -> str:
        return pulumi.get(self, "color")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def value(self) -> str:
        return pulumi.get(self, "value")


class AwaitableGetCustomFieldOptionResult(GetCustomFieldOptionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCustomFieldOptionResult(
            color=self.color,
            id=self.id,
            value=self.value)


def get_custom_field_option(color: Optional[str] = None,
                            value: Optional[str] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCustomFieldOptionResult:
    """
    DEPRECATED: Please use `form_field` and `form_field_option` data sources instead.

    ## Example Usage
    """
    __args__ = dict()
    __args__['color'] = color
    __args__['value'] = value
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('rootly:index/getCustomFieldOption:getCustomFieldOption', __args__, opts=opts, typ=GetCustomFieldOptionResult).value

    return AwaitableGetCustomFieldOptionResult(
        color=pulumi.get(__ret__, 'color'),
        id=pulumi.get(__ret__, 'id'),
        value=pulumi.get(__ret__, 'value'))


@_utilities.lift_output_func(get_custom_field_option)
def get_custom_field_option_output(color: Optional[pulumi.Input[Optional[str]]] = None,
                                   value: Optional[pulumi.Input[Optional[str]]] = None,
                                   opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetCustomFieldOptionResult]:
    """
    DEPRECATED: Please use `form_field` and `form_field_option` data sources instead.

    ## Example Usage
    """
    ...
