# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetFormFieldPositionResult',
    'AwaitableGetFormFieldPositionResult',
    'get_form_field_position',
    'get_form_field_position_output',
]

@pulumi.output_type
class GetFormFieldPositionResult:
    """
    A collection of values returned by getFormFieldPosition.
    """
    def __init__(__self__, form=None, id=None):
        if form and not isinstance(form, str):
            raise TypeError("Expected argument 'form' to be a str")
        pulumi.set(__self__, "form", form)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @property
    @pulumi.getter
    def form(self) -> str:
        return pulumi.get(self, "form")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "id")


class AwaitableGetFormFieldPositionResult(GetFormFieldPositionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetFormFieldPositionResult(
            form=self.form,
            id=self.id)


def get_form_field_position(form: Optional[str] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetFormFieldPositionResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['form'] = form
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('rootly:index/getFormFieldPosition:getFormFieldPosition', __args__, opts=opts, typ=GetFormFieldPositionResult).value

    return AwaitableGetFormFieldPositionResult(
        form=pulumi.get(__ret__, 'form'),
        id=pulumi.get(__ret__, 'id'))


@_utilities.lift_output_func(get_form_field_position)
def get_form_field_position_output(form: Optional[pulumi.Input[Optional[str]]] = None,
                                   opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetFormFieldPositionResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
