// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rootly.Inputs
{

    public sealed class AlertsSourceSourceableAttributesArgs : global::Pulumi.ResourceArgs
    {
        [Input("autoResolve")]
        public Input<bool>? AutoResolve { get; set; }

        [Input("fieldMappingsAttributes")]
        private InputList<Inputs.AlertsSourceSourceableAttributesFieldMappingsAttributeArgs>? _fieldMappingsAttributes;
        public InputList<Inputs.AlertsSourceSourceableAttributesFieldMappingsAttributeArgs> FieldMappingsAttributes
        {
            get => _fieldMappingsAttributes ?? (_fieldMappingsAttributes = new InputList<Inputs.AlertsSourceSourceableAttributesFieldMappingsAttributeArgs>());
            set => _fieldMappingsAttributes = value;
        }

        /// <summary>
        /// This value is matched with the value extracted from alerts payload using JSON path in field*mappings*attributes
        /// </summary>
        [Input("resolveState")]
        public Input<string>? ResolveState { get; set; }

        public AlertsSourceSourceableAttributesArgs()
        {
        }
        public static new AlertsSourceSourceableAttributesArgs Empty => new AlertsSourceSourceableAttributesArgs();
    }
}
