// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rootly.Inputs
{

    public sealed class DashboardPanelParamsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("datasets")]
        private InputList<Inputs.DashboardPanelParamsDatasetGetArgs>? _datasets;
        public InputList<Inputs.DashboardPanelParamsDatasetGetArgs> Datasets
        {
            get => _datasets ?? (_datasets = new InputList<Inputs.DashboardPanelParamsDatasetGetArgs>());
            set => _datasets = value;
        }

        [Input("display", required: true)]
        public Input<string> Display { get; set; } = null!;

        [Input("legend")]
        public Input<Inputs.DashboardPanelParamsLegendGetArgs>? Legend { get; set; }

        public DashboardPanelParamsGetArgs()
        {
        }
        public static new DashboardPanelParamsGetArgs Empty => new DashboardPanelParamsGetArgs();
    }
}
