// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rootly.Inputs
{

    public sealed class WorkflowTaskCreateQuipPageTaskParamsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The page content
        /// </summary>
        [Input("content")]
        public Input<string>? Content { get; set; }

        /// <summary>
        /// Value must be one of true or false
        /// </summary>
        [Input("markPostMortemAsPublished")]
        public Input<bool>? MarkPostMortemAsPublished { get; set; }

        /// <summary>
        /// The parent folder id
        /// </summary>
        [Input("parentFolderId")]
        public Input<string>? ParentFolderId { get; set; }

        /// <summary>
        /// Retrospective template to use when creating page, if desired
        /// </summary>
        [Input("postMortemTemplateId")]
        public Input<string>? PostMortemTemplateId { get; set; }

        [Input("taskType")]
        public Input<string>? TaskType { get; set; }

        /// <summary>
        /// The Quip file ID to use as a template
        /// </summary>
        [Input("templateId")]
        public Input<string>? TemplateId { get; set; }

        /// <summary>
        /// The page title
        /// </summary>
        [Input("title", required: true)]
        public Input<string> Title { get; set; } = null!;

        public WorkflowTaskCreateQuipPageTaskParamsArgs()
        {
        }
        public static new WorkflowTaskCreateQuipPageTaskParamsArgs Empty => new WorkflowTaskCreateQuipPageTaskParamsArgs();
    }
}
