// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rootly.Inputs
{

    public sealed class WorkflowTaskAutoAssignRolePagerdutyTaskParamsArgs : global::Pulumi.ResourceArgs
    {
        [Input("escalationPolicy")]
        private InputMap<string>? _escalationPolicy;

        /// <summary>
        /// Map must contain two fields, `id` and `name`.
        /// </summary>
        public InputMap<string> EscalationPolicy
        {
            get => _escalationPolicy ?? (_escalationPolicy = new InputMap<string>());
            set => _escalationPolicy = value;
        }

        /// <summary>
        /// The role id
        /// </summary>
        [Input("incidentRoleId", required: true)]
        public Input<string> IncidentRoleId { get; set; } = null!;

        [Input("schedule")]
        private InputMap<string>? _schedule;

        /// <summary>
        /// Map must contain two fields, `id` and `name`.
        /// </summary>
        public InputMap<string> Schedule
        {
            get => _schedule ?? (_schedule = new InputMap<string>());
            set => _schedule = value;
        }

        [Input("service")]
        private InputMap<string>? _service;

        /// <summary>
        /// Map must contain two fields, `id` and `name`.
        /// </summary>
        public InputMap<string> Service
        {
            get => _service ?? (_service = new InputMap<string>());
            set => _service = value;
        }

        [Input("taskType")]
        public Input<string>? TaskType { get; set; }

        public WorkflowTaskAutoAssignRolePagerdutyTaskParamsArgs()
        {
        }
        public static new WorkflowTaskAutoAssignRolePagerdutyTaskParamsArgs Empty => new WorkflowTaskAutoAssignRolePagerdutyTaskParamsArgs();
    }
}
