// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rootly.Inputs
{

    public sealed class WorkflowTaskRedisClientTaskParamsArgs : global::Pulumi.ResourceArgs
    {
        [Input("commands", required: true)]
        public Input<string> Commands { get; set; } = null!;

        [Input("eventMessage")]
        public Input<string>? EventMessage { get; set; }

        [Input("eventUrl")]
        public Input<string>? EventUrl { get; set; }

        /// <summary>
        /// Value must be one of true or false
        /// </summary>
        [Input("postToIncidentTimeline")]
        public Input<bool>? PostToIncidentTimeline { get; set; }

        [Input("postToSlackChannels")]
        private InputList<Inputs.WorkflowTaskRedisClientTaskParamsPostToSlackChannelArgs>? _postToSlackChannels;
        public InputList<Inputs.WorkflowTaskRedisClientTaskParamsPostToSlackChannelArgs> PostToSlackChannels
        {
            get => _postToSlackChannels ?? (_postToSlackChannels = new InputList<Inputs.WorkflowTaskRedisClientTaskParamsPostToSlackChannelArgs>());
            set => _postToSlackChannels = value;
        }

        [Input("taskType")]
        public Input<string>? TaskType { get; set; }

        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public WorkflowTaskRedisClientTaskParamsArgs()
        {
        }
        public static new WorkflowTaskRedisClientTaskParamsArgs Empty => new WorkflowTaskRedisClientTaskParamsArgs();
    }
}
