// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getHeartbeat(args?: GetHeartbeatArgs, opts?: pulumi.InvokeOptions): Promise<GetHeartbeatResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("rootly:index/getHeartbeat:getHeartbeat", {
        "createdAt": args.createdAt,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getHeartbeat.
 */
export interface GetHeartbeatArgs {
    /**
     * Filter by date range using 'lt' and 'gt'.
     */
    createdAt?: {[key: string]: string};
    name?: string;
}

/**
 * A collection of values returned by getHeartbeat.
 */
export interface GetHeartbeatResult {
    /**
     * Filter by date range using 'lt' and 'gt'.
     */
    readonly createdAt?: {[key: string]: string};
    /**
     * The ID of this resource.
     */
    readonly id: string;
    readonly name: string;
}
export function getHeartbeatOutput(args?: GetHeartbeatOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetHeartbeatResult> {
    return pulumi.output(args).apply((a: any) => getHeartbeat(a, opts))
}

/**
 * A collection of arguments for invoking getHeartbeat.
 */
export interface GetHeartbeatOutputArgs {
    /**
     * Filter by date range using 'lt' and 'gt'.
     */
    createdAt?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    name?: pulumi.Input<string>;
}
