// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getIncidentRoles(args?: GetIncidentRolesArgs, opts?: pulumi.InvokeOptions): Promise<GetIncidentRolesResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("rootly:index/getIncidentRoles:getIncidentRoles", {
        "enabled": args.enabled,
        "name": args.name,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getIncidentRoles.
 */
export interface GetIncidentRolesArgs {
    enabled?: boolean;
    name?: string;
    slug?: string;
}

/**
 * A collection of values returned by getIncidentRoles.
 */
export interface GetIncidentRolesResult {
    readonly enabled?: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly incidentRoles: outputs.GetIncidentRolesIncidentRole[];
    readonly name?: string;
    readonly slug?: string;
}

export function getIncidentRolesOutput(args?: GetIncidentRolesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIncidentRolesResult> {
    return pulumi.output(args).apply(a => getIncidentRoles(a, opts))
}

/**
 * A collection of arguments for invoking getIncidentRoles.
 */
export interface GetIncidentRolesOutputArgs {
    enabled?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    slug?: pulumi.Input<string>;
}
