// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getLiveCallRouter(args?: GetLiveCallRouterArgs, opts?: pulumi.InvokeOptions): Promise<GetLiveCallRouterResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("rootly:index/getLiveCallRouter:getLiveCallRouter", {
        "createdAt": args.createdAt,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getLiveCallRouter.
 */
export interface GetLiveCallRouterArgs {
    /**
     * Filter by date range using 'lt' and 'gt'.
     */
    createdAt?: {[key: string]: string};
    name?: string;
}

/**
 * A collection of values returned by getLiveCallRouter.
 */
export interface GetLiveCallRouterResult {
    /**
     * Filter by date range using 'lt' and 'gt'.
     */
    readonly createdAt?: {[key: string]: string};
    /**
     * The ID of this resource.
     */
    readonly id: string;
    readonly name: string;
}
export function getLiveCallRouterOutput(args?: GetLiveCallRouterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLiveCallRouterResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("rootly:index/getLiveCallRouter:getLiveCallRouter", {
        "createdAt": args.createdAt,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getLiveCallRouter.
 */
export interface GetLiveCallRouterOutputArgs {
    /**
     * Filter by date range using 'lt' and 'gt'.
     */
    createdAt?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    name?: pulumi.Input<string | undefined>;
}
