// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 */
export function getOnCallRole(args?: GetOnCallRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetOnCallRoleResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("rootly:index/getOnCallRole:getOnCallRole", {
        "createdAt": args.createdAt,
        "name": args.name,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getOnCallRole.
 */
export interface GetOnCallRoleArgs {
    /**
     * Filter by date range using 'lt' and 'gt'.
     */
    createdAt?: {[key: string]: string};
    name?: string;
    slug?: string;
}

/**
 * A collection of values returned by getOnCallRole.
 */
export interface GetOnCallRoleResult {
    /**
     * Filter by date range using 'lt' and 'gt'.
     */
    readonly createdAt?: {[key: string]: string};
    /**
     * The ID of this resource.
     */
    readonly id: string;
    readonly name: string;
    readonly slug: string;
}
/**
 * ## Example Usage
 */
export function getOnCallRoleOutput(args?: GetOnCallRoleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOnCallRoleResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("rootly:index/getOnCallRole:getOnCallRole", {
        "createdAt": args.createdAt,
        "name": args.name,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getOnCallRole.
 */
export interface GetOnCallRoleOutputArgs {
    /**
     * Filter by date range using 'lt' and 'gt'.
     */
    createdAt?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    name?: pulumi.Input<string | undefined>;
    slug?: pulumi.Input<string | undefined>;
}
