// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Import
 *
 * Using `pulumi import`, import rootly.IncidentRole using the `id`. For example:
 *
 * ```sh
 * $ pulumi import rootly:index/incidentRole:IncidentRole my-resource my-resource-slug
 * ```
 */
export class IncidentRole extends pulumi.CustomResource {
    /**
     * Get an existing IncidentRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IncidentRoleState, opts?: pulumi.CustomResourceOptions): IncidentRole {
        return new IncidentRole(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'rootly:index/incidentRole:IncidentRole';

    /**
     * Returns true if the given object is an instance of IncidentRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IncidentRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IncidentRole.__pulumiType;
    }

    /**
     * Value must be one of true or false
     */
    declare public readonly allowMultiUserAssignment: pulumi.Output<boolean>;
    /**
     * The description of the incident role
     */
    declare public readonly description: pulumi.Output<string>;
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * The name of the incident role
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Value must be one of true or false
     */
    declare public readonly optional: pulumi.Output<boolean>;
    /**
     * Position of the incident role
     */
    declare public readonly position: pulumi.Output<number>;
    /**
     * The slug of the incident role
     */
    declare public readonly slug: pulumi.Output<string>;
    /**
     * The summary of the incident role
     */
    declare public readonly summary: pulumi.Output<string>;

    /**
     * Create a IncidentRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IncidentRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IncidentRoleArgs | IncidentRoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IncidentRoleState | undefined;
            resourceInputs["allowMultiUserAssignment"] = state?.allowMultiUserAssignment;
            resourceInputs["description"] = state?.description;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["optional"] = state?.optional;
            resourceInputs["position"] = state?.position;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["summary"] = state?.summary;
        } else {
            const args = argsOrState as IncidentRoleArgs | undefined;
            resourceInputs["allowMultiUserAssignment"] = args?.allowMultiUserAssignment;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["optional"] = args?.optional;
            resourceInputs["position"] = args?.position;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["summary"] = args?.summary;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IncidentRole.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IncidentRole resources.
 */
export interface IncidentRoleState {
    /**
     * Value must be one of true or false
     */
    allowMultiUserAssignment?: pulumi.Input<boolean>;
    /**
     * The description of the incident role
     */
    description?: pulumi.Input<string>;
    enabled?: pulumi.Input<boolean>;
    /**
     * The name of the incident role
     */
    name?: pulumi.Input<string>;
    /**
     * Value must be one of true or false
     */
    optional?: pulumi.Input<boolean>;
    /**
     * Position of the incident role
     */
    position?: pulumi.Input<number>;
    /**
     * The slug of the incident role
     */
    slug?: pulumi.Input<string>;
    /**
     * The summary of the incident role
     */
    summary?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IncidentRole resource.
 */
export interface IncidentRoleArgs {
    /**
     * Value must be one of true or false
     */
    allowMultiUserAssignment?: pulumi.Input<boolean>;
    /**
     * The description of the incident role
     */
    description?: pulumi.Input<string>;
    enabled?: pulumi.Input<boolean>;
    /**
     * The name of the incident role
     */
    name?: pulumi.Input<string>;
    /**
     * Value must be one of true or false
     */
    optional?: pulumi.Input<boolean>;
    /**
     * Position of the incident role
     */
    position?: pulumi.Input<number>;
    /**
     * The slug of the incident role
     */
    slug?: pulumi.Input<string>;
    /**
     * The summary of the incident role
     */
    summary?: pulumi.Input<string>;
}
