// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ## Import
 *
 * Using `pulumi import`, import rootly.ScheduleRotationUser using the `id`. For example:
 *
 * ```sh
 * $ pulumi import rootly:index/scheduleRotationUser:ScheduleRotationUser my-resource 00000000-0000-0000-0000-000000000000
 * ```
 */
export class ScheduleRotationUser extends pulumi.CustomResource {
    /**
     * Get an existing ScheduleRotationUser resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ScheduleRotationUserState, opts?: pulumi.CustomResourceOptions): ScheduleRotationUser {
        return new ScheduleRotationUser(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'rootly:index/scheduleRotationUser:ScheduleRotationUser';

    /**
     * Returns true if the given object is an instance of ScheduleRotationUser.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ScheduleRotationUser {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ScheduleRotationUser.__pulumiType;
    }

    /**
     * Position of the user inside rotation
     */
    declare public readonly position: pulumi.Output<number>;
    declare public readonly scheduleRotationId: pulumi.Output<string>;
    /**
     * Schedule rotation user
     */
    declare public readonly userId: pulumi.Output<number>;

    /**
     * Create a ScheduleRotationUser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ScheduleRotationUserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ScheduleRotationUserArgs | ScheduleRotationUserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ScheduleRotationUserState | undefined;
            resourceInputs["position"] = state?.position;
            resourceInputs["scheduleRotationId"] = state?.scheduleRotationId;
            resourceInputs["userId"] = state?.userId;
        } else {
            const args = argsOrState as ScheduleRotationUserArgs | undefined;
            if (args?.userId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userId'");
            }
            resourceInputs["position"] = args?.position;
            resourceInputs["scheduleRotationId"] = args?.scheduleRotationId;
            resourceInputs["userId"] = args?.userId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ScheduleRotationUser.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ScheduleRotationUser resources.
 */
export interface ScheduleRotationUserState {
    /**
     * Position of the user inside rotation
     */
    position?: pulumi.Input<number>;
    scheduleRotationId?: pulumi.Input<string>;
    /**
     * Schedule rotation user
     */
    userId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a ScheduleRotationUser resource.
 */
export interface ScheduleRotationUserArgs {
    /**
     * Position of the user inside rotation
     */
    position?: pulumi.Input<number>;
    scheduleRotationId?: pulumi.Input<string>;
    /**
     * Schedule rotation user
     */
    userId: pulumi.Input<number>;
}
