// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ## Import
 *
 * rootly.Service can be imported using the `import` command.
 *
 * ```sh
 * $ pulumi import rootly:index/service:Service primary a816421c-6ceb-481a-87c4-585e47451f24
 * ```
 *
 * Or using an `import` block.
 *
 * Locate the resource id in the web app, or retrieve it by listing resources through the API if it's not visible in the web app.
 *
 * HCL can be generated from the import block using the `-generate-config-out` flag.
 *
 * ```sh
 * pulumi preview -generate-config-out=generated.tf
 * ```
 */
export class Service extends pulumi.CustomResource {
    /**
     * Get an existing Service resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceState, opts?: pulumi.CustomResourceOptions): Service {
        return new Service(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'rootly:index/service:Service';

    /**
     * Returns true if the given object is an instance of Service.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Service {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Service.__pulumiType;
    }

    /**
     * Map must contain two fields, `id` and `name`. Slack channel to broadcast alerts to
     */
    declare public readonly alertBroadcastChannel: pulumi.Output<outputs.ServiceAlertBroadcastChannel>;
    /**
     * Enable alerts to be broadcasted to a specific channel. Value must be one of true or false
     */
    declare public readonly alertBroadcastEnabled: pulumi.Output<boolean>;
    /**
     * The alert urgency id of the service
     */
    declare public readonly alertUrgencyId: pulumi.Output<string>;
    /**
     * Email generated to send alerts to
     */
    declare public readonly alertsEmailAddress: pulumi.Output<string>;
    /**
     * Enable alerts through email. Value must be one of true or false
     */
    declare public readonly alertsEmailEnabled: pulumi.Output<boolean>;
    /**
     * The Backstage entity id associated to this service. eg: :namespace/:kind/:entity_name
     */
    declare public readonly backstageId: pulumi.Output<string | undefined>;
    /**
     * The hex color of the service
     */
    declare public readonly color: pulumi.Output<string>;
    /**
     * The Cortex group id associated to this service
     */
    declare public readonly cortexId: pulumi.Output<string | undefined>;
    /**
     * The description of the service
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Environments associated with this service
     */
    declare public readonly environmentIds: pulumi.Output<string[]>;
    /**
     * The escalation policy id of the service
     */
    declare public readonly escalationPolicyId: pulumi.Output<string>;
    /**
     * The external id associated to this service
     */
    declare public readonly externalId: pulumi.Output<string | undefined>;
    /**
     * The GitHub repository branch associated to this service. eg: main
     */
    declare public readonly githubRepositoryBranch: pulumi.Output<string>;
    /**
     * The GitHub repository name associated to this service. eg: rootlyhq/my-service
     */
    declare public readonly githubRepositoryName: pulumi.Output<string>;
    /**
     * The GitLab repository branch associated to this service. eg: main
     */
    declare public readonly gitlabRepositoryBranch: pulumi.Output<string>;
    /**
     * The GitLab repository name associated to this service. eg: rootlyhq/my-service
     */
    declare public readonly gitlabRepositoryName: pulumi.Output<string>;
    /**
     * Map must contain two fields, `id` and `name`. Slack channel to broadcast incidents to
     */
    declare public readonly incidentBroadcastChannel: pulumi.Output<outputs.ServiceIncidentBroadcastChannel>;
    /**
     * Enable incidents to be broadcasted to a specific channel. Value must be one of true or false
     */
    declare public readonly incidentBroadcastEnabled: pulumi.Output<boolean>;
    /**
     * The Kubernetes deployment name associated to this service. eg: namespace/deployment-name
     */
    declare public readonly kubernetesDeploymentName: pulumi.Output<string>;
    /**
     * The name of the service
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Emails attached to the service
     */
    declare public readonly notifyEmails: pulumi.Output<string[] | undefined>;
    /**
     * The Opsgenie service id associated to this service
     */
    declare public readonly opsgenieId: pulumi.Output<string | undefined>;
    /**
     * Owner Teams associated with this service
     */
    declare public readonly ownerGroupIds: pulumi.Output<string[]>;
    /**
     * Owner Users associated with this service
     */
    declare public readonly ownerUserIds: pulumi.Output<number[]>;
    /**
     * The PagerDuty service id associated to this service
     */
    declare public readonly pagerdutyId: pulumi.Output<string | undefined>;
    /**
     * Position of the service
     */
    declare public readonly position: pulumi.Output<number>;
    /**
     * Array of property values for this service.
     */
    declare public readonly properties: pulumi.Output<outputs.ServiceProperty[] | undefined>;
    /**
     * The public description of the service
     */
    declare public readonly publicDescription: pulumi.Output<string>;
    /**
     * Services dependent on this service
     */
    declare public readonly serviceIds: pulumi.Output<string[]>;
    /**
     * The Service Now CI sys id associated to this service
     */
    declare public readonly serviceNowCiSysId: pulumi.Output<string | undefined>;
    /**
     * Slack Aliases associated with this service
     */
    declare public readonly slackAliases: pulumi.Output<outputs.ServiceSlackAlias[] | undefined>;
    /**
     * Slack Channels associated with this service
     */
    declare public readonly slackChannels: pulumi.Output<outputs.ServiceSlackChannel[] | undefined>;
    /**
     * The slug of the service
     */
    declare public /*out*/ readonly slug: pulumi.Output<string>;

    /**
     * Create a Service resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ServiceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceArgs | ServiceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceState | undefined;
            resourceInputs["alertBroadcastChannel"] = state?.alertBroadcastChannel;
            resourceInputs["alertBroadcastEnabled"] = state?.alertBroadcastEnabled;
            resourceInputs["alertUrgencyId"] = state?.alertUrgencyId;
            resourceInputs["alertsEmailAddress"] = state?.alertsEmailAddress;
            resourceInputs["alertsEmailEnabled"] = state?.alertsEmailEnabled;
            resourceInputs["backstageId"] = state?.backstageId;
            resourceInputs["color"] = state?.color;
            resourceInputs["cortexId"] = state?.cortexId;
            resourceInputs["description"] = state?.description;
            resourceInputs["environmentIds"] = state?.environmentIds;
            resourceInputs["escalationPolicyId"] = state?.escalationPolicyId;
            resourceInputs["externalId"] = state?.externalId;
            resourceInputs["githubRepositoryBranch"] = state?.githubRepositoryBranch;
            resourceInputs["githubRepositoryName"] = state?.githubRepositoryName;
            resourceInputs["gitlabRepositoryBranch"] = state?.gitlabRepositoryBranch;
            resourceInputs["gitlabRepositoryName"] = state?.gitlabRepositoryName;
            resourceInputs["incidentBroadcastChannel"] = state?.incidentBroadcastChannel;
            resourceInputs["incidentBroadcastEnabled"] = state?.incidentBroadcastEnabled;
            resourceInputs["kubernetesDeploymentName"] = state?.kubernetesDeploymentName;
            resourceInputs["name"] = state?.name;
            resourceInputs["notifyEmails"] = state?.notifyEmails;
            resourceInputs["opsgenieId"] = state?.opsgenieId;
            resourceInputs["ownerGroupIds"] = state?.ownerGroupIds;
            resourceInputs["ownerUserIds"] = state?.ownerUserIds;
            resourceInputs["pagerdutyId"] = state?.pagerdutyId;
            resourceInputs["position"] = state?.position;
            resourceInputs["properties"] = state?.properties;
            resourceInputs["publicDescription"] = state?.publicDescription;
            resourceInputs["serviceIds"] = state?.serviceIds;
            resourceInputs["serviceNowCiSysId"] = state?.serviceNowCiSysId;
            resourceInputs["slackAliases"] = state?.slackAliases;
            resourceInputs["slackChannels"] = state?.slackChannels;
            resourceInputs["slug"] = state?.slug;
        } else {
            const args = argsOrState as ServiceArgs | undefined;
            resourceInputs["alertBroadcastChannel"] = args?.alertBroadcastChannel;
            resourceInputs["alertBroadcastEnabled"] = args?.alertBroadcastEnabled;
            resourceInputs["alertUrgencyId"] = args?.alertUrgencyId;
            resourceInputs["alertsEmailAddress"] = args?.alertsEmailAddress;
            resourceInputs["alertsEmailEnabled"] = args?.alertsEmailEnabled;
            resourceInputs["backstageId"] = args?.backstageId;
            resourceInputs["color"] = args?.color;
            resourceInputs["cortexId"] = args?.cortexId;
            resourceInputs["description"] = args?.description;
            resourceInputs["environmentIds"] = args?.environmentIds;
            resourceInputs["escalationPolicyId"] = args?.escalationPolicyId;
            resourceInputs["externalId"] = args?.externalId;
            resourceInputs["githubRepositoryBranch"] = args?.githubRepositoryBranch;
            resourceInputs["githubRepositoryName"] = args?.githubRepositoryName;
            resourceInputs["gitlabRepositoryBranch"] = args?.gitlabRepositoryBranch;
            resourceInputs["gitlabRepositoryName"] = args?.gitlabRepositoryName;
            resourceInputs["incidentBroadcastChannel"] = args?.incidentBroadcastChannel;
            resourceInputs["incidentBroadcastEnabled"] = args?.incidentBroadcastEnabled;
            resourceInputs["kubernetesDeploymentName"] = args?.kubernetesDeploymentName;
            resourceInputs["name"] = args?.name;
            resourceInputs["notifyEmails"] = args?.notifyEmails;
            resourceInputs["opsgenieId"] = args?.opsgenieId;
            resourceInputs["ownerGroupIds"] = args?.ownerGroupIds;
            resourceInputs["ownerUserIds"] = args?.ownerUserIds;
            resourceInputs["pagerdutyId"] = args?.pagerdutyId;
            resourceInputs["position"] = args?.position;
            resourceInputs["properties"] = args?.properties;
            resourceInputs["publicDescription"] = args?.publicDescription;
            resourceInputs["serviceIds"] = args?.serviceIds;
            resourceInputs["serviceNowCiSysId"] = args?.serviceNowCiSysId;
            resourceInputs["slackAliases"] = args?.slackAliases;
            resourceInputs["slackChannels"] = args?.slackChannels;
            resourceInputs["slug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Service.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Service resources.
 */
export interface ServiceState {
    /**
     * Map must contain two fields, `id` and `name`. Slack channel to broadcast alerts to
     */
    alertBroadcastChannel?: pulumi.Input<inputs.ServiceAlertBroadcastChannel | undefined>;
    /**
     * Enable alerts to be broadcasted to a specific channel. Value must be one of true or false
     */
    alertBroadcastEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * The alert urgency id of the service
     */
    alertUrgencyId?: pulumi.Input<string | undefined>;
    /**
     * Email generated to send alerts to
     */
    alertsEmailAddress?: pulumi.Input<string | undefined>;
    /**
     * Enable alerts through email. Value must be one of true or false
     */
    alertsEmailEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * The Backstage entity id associated to this service. eg: :namespace/:kind/:entity_name
     */
    backstageId?: pulumi.Input<string | undefined>;
    /**
     * The hex color of the service
     */
    color?: pulumi.Input<string | undefined>;
    /**
     * The Cortex group id associated to this service
     */
    cortexId?: pulumi.Input<string | undefined>;
    /**
     * The description of the service
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Environments associated with this service
     */
    environmentIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The escalation policy id of the service
     */
    escalationPolicyId?: pulumi.Input<string | undefined>;
    /**
     * The external id associated to this service
     */
    externalId?: pulumi.Input<string | undefined>;
    /**
     * The GitHub repository branch associated to this service. eg: main
     */
    githubRepositoryBranch?: pulumi.Input<string | undefined>;
    /**
     * The GitHub repository name associated to this service. eg: rootlyhq/my-service
     */
    githubRepositoryName?: pulumi.Input<string | undefined>;
    /**
     * The GitLab repository branch associated to this service. eg: main
     */
    gitlabRepositoryBranch?: pulumi.Input<string | undefined>;
    /**
     * The GitLab repository name associated to this service. eg: rootlyhq/my-service
     */
    gitlabRepositoryName?: pulumi.Input<string | undefined>;
    /**
     * Map must contain two fields, `id` and `name`. Slack channel to broadcast incidents to
     */
    incidentBroadcastChannel?: pulumi.Input<inputs.ServiceIncidentBroadcastChannel | undefined>;
    /**
     * Enable incidents to be broadcasted to a specific channel. Value must be one of true or false
     */
    incidentBroadcastEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * The Kubernetes deployment name associated to this service. eg: namespace/deployment-name
     */
    kubernetesDeploymentName?: pulumi.Input<string | undefined>;
    /**
     * The name of the service
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Emails attached to the service
     */
    notifyEmails?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The Opsgenie service id associated to this service
     */
    opsgenieId?: pulumi.Input<string | undefined>;
    /**
     * Owner Teams associated with this service
     */
    ownerGroupIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Owner Users associated with this service
     */
    ownerUserIds?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    /**
     * The PagerDuty service id associated to this service
     */
    pagerdutyId?: pulumi.Input<string | undefined>;
    /**
     * Position of the service
     */
    position?: pulumi.Input<number | undefined>;
    /**
     * Array of property values for this service.
     */
    properties?: pulumi.Input<pulumi.Input<inputs.ServiceProperty>[] | undefined>;
    /**
     * The public description of the service
     */
    publicDescription?: pulumi.Input<string | undefined>;
    /**
     * Services dependent on this service
     */
    serviceIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The Service Now CI sys id associated to this service
     */
    serviceNowCiSysId?: pulumi.Input<string | undefined>;
    /**
     * Slack Aliases associated with this service
     */
    slackAliases?: pulumi.Input<pulumi.Input<inputs.ServiceSlackAlias>[] | undefined>;
    /**
     * Slack Channels associated with this service
     */
    slackChannels?: pulumi.Input<pulumi.Input<inputs.ServiceSlackChannel>[] | undefined>;
    /**
     * The slug of the service
     */
    slug?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Service resource.
 */
export interface ServiceArgs {
    /**
     * Map must contain two fields, `id` and `name`. Slack channel to broadcast alerts to
     */
    alertBroadcastChannel?: pulumi.Input<inputs.ServiceAlertBroadcastChannel | undefined>;
    /**
     * Enable alerts to be broadcasted to a specific channel. Value must be one of true or false
     */
    alertBroadcastEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * The alert urgency id of the service
     */
    alertUrgencyId?: pulumi.Input<string | undefined>;
    /**
     * Email generated to send alerts to
     */
    alertsEmailAddress?: pulumi.Input<string | undefined>;
    /**
     * Enable alerts through email. Value must be one of true or false
     */
    alertsEmailEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * The Backstage entity id associated to this service. eg: :namespace/:kind/:entity_name
     */
    backstageId?: pulumi.Input<string | undefined>;
    /**
     * The hex color of the service
     */
    color?: pulumi.Input<string | undefined>;
    /**
     * The Cortex group id associated to this service
     */
    cortexId?: pulumi.Input<string | undefined>;
    /**
     * The description of the service
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Environments associated with this service
     */
    environmentIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The escalation policy id of the service
     */
    escalationPolicyId?: pulumi.Input<string | undefined>;
    /**
     * The external id associated to this service
     */
    externalId?: pulumi.Input<string | undefined>;
    /**
     * The GitHub repository branch associated to this service. eg: main
     */
    githubRepositoryBranch?: pulumi.Input<string | undefined>;
    /**
     * The GitHub repository name associated to this service. eg: rootlyhq/my-service
     */
    githubRepositoryName?: pulumi.Input<string | undefined>;
    /**
     * The GitLab repository branch associated to this service. eg: main
     */
    gitlabRepositoryBranch?: pulumi.Input<string | undefined>;
    /**
     * The GitLab repository name associated to this service. eg: rootlyhq/my-service
     */
    gitlabRepositoryName?: pulumi.Input<string | undefined>;
    /**
     * Map must contain two fields, `id` and `name`. Slack channel to broadcast incidents to
     */
    incidentBroadcastChannel?: pulumi.Input<inputs.ServiceIncidentBroadcastChannel | undefined>;
    /**
     * Enable incidents to be broadcasted to a specific channel. Value must be one of true or false
     */
    incidentBroadcastEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * The Kubernetes deployment name associated to this service. eg: namespace/deployment-name
     */
    kubernetesDeploymentName?: pulumi.Input<string | undefined>;
    /**
     * The name of the service
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Emails attached to the service
     */
    notifyEmails?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The Opsgenie service id associated to this service
     */
    opsgenieId?: pulumi.Input<string | undefined>;
    /**
     * Owner Teams associated with this service
     */
    ownerGroupIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Owner Users associated with this service
     */
    ownerUserIds?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    /**
     * The PagerDuty service id associated to this service
     */
    pagerdutyId?: pulumi.Input<string | undefined>;
    /**
     * Position of the service
     */
    position?: pulumi.Input<number | undefined>;
    /**
     * Array of property values for this service.
     */
    properties?: pulumi.Input<pulumi.Input<inputs.ServiceProperty>[] | undefined>;
    /**
     * The public description of the service
     */
    publicDescription?: pulumi.Input<string | undefined>;
    /**
     * Services dependent on this service
     */
    serviceIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The Service Now CI sys id associated to this service
     */
    serviceNowCiSysId?: pulumi.Input<string | undefined>;
    /**
     * Slack Aliases associated with this service
     */
    slackAliases?: pulumi.Input<pulumi.Input<inputs.ServiceSlackAlias>[] | undefined>;
    /**
     * Slack Channels associated with this service
     */
    slackChannels?: pulumi.Input<pulumi.Input<inputs.ServiceSlackChannel>[] | undefined>;
}
