// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Import
 *
 * rootly.StatusPageAnnouncement can be imported using the `import` command.
 *
 * ```sh
 * $ pulumi import rootly:index/statusPageAnnouncement:StatusPageAnnouncement primary a816421c-6ceb-481a-87c4-585e47451f24
 * ```
 *
 * Or using an `import` block.
 *
 * Locate the resource id in the web app, or retrieve it by listing resources through the API if it's not visible in the web app.
 *
 * HCL can be generated from the import block using the `-generate-config-out` flag.
 *
 * ```sh
 * pulumi preview -generate-config-out=generated.tf
 * ```
 */
export class StatusPageAnnouncement extends pulumi.CustomResource {
    /**
     * Get an existing StatusPageAnnouncement resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StatusPageAnnouncementState, opts?: pulumi.CustomResourceOptions): StatusPageAnnouncement {
        return new StatusPageAnnouncement(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'rootly:index/statusPageAnnouncement:StatusPageAnnouncement';

    /**
     * Returns true if the given object is an instance of StatusPageAnnouncement.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StatusPageAnnouncement {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StatusPageAnnouncement.__pulumiType;
    }

    /**
     * Body of the announcement
     */
    declare public readonly body: pulumi.Output<string>;
    /**
     * Controls if status page subscribers should be notified. Defaults to true. Value must be one of true or false
     */
    declare public readonly notifySubscribers: pulumi.Output<boolean | undefined>;
    /**
     * Date the announcement was published
     */
    declare public /*out*/ readonly publishedAt: pulumi.Output<string>;
    /**
     * ID of the status page the announcement was posted to
     */
    declare public readonly statusPageId: pulumi.Output<string>;
    /**
     * Title of the announcement
     */
    declare public readonly title: pulumi.Output<string>;
    /**
     * ID of the user who posted the announcement
     */
    declare public /*out*/ readonly userId: pulumi.Output<number>;

    /**
     * Create a StatusPageAnnouncement resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StatusPageAnnouncementArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StatusPageAnnouncementArgs | StatusPageAnnouncementState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StatusPageAnnouncementState | undefined;
            resourceInputs["body"] = state?.body;
            resourceInputs["notifySubscribers"] = state?.notifySubscribers;
            resourceInputs["publishedAt"] = state?.publishedAt;
            resourceInputs["statusPageId"] = state?.statusPageId;
            resourceInputs["title"] = state?.title;
            resourceInputs["userId"] = state?.userId;
        } else {
            const args = argsOrState as StatusPageAnnouncementArgs | undefined;
            if (args?.body === undefined && !opts.urn) {
                throw new Error("Missing required property 'body'");
            }
            if (args?.statusPageId === undefined && !opts.urn) {
                throw new Error("Missing required property 'statusPageId'");
            }
            if (args?.title === undefined && !opts.urn) {
                throw new Error("Missing required property 'title'");
            }
            resourceInputs["body"] = args?.body;
            resourceInputs["notifySubscribers"] = args?.notifySubscribers;
            resourceInputs["statusPageId"] = args?.statusPageId;
            resourceInputs["title"] = args?.title;
            resourceInputs["publishedAt"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StatusPageAnnouncement.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering StatusPageAnnouncement resources.
 */
export interface StatusPageAnnouncementState {
    /**
     * Body of the announcement
     */
    body?: pulumi.Input<string | undefined>;
    /**
     * Controls if status page subscribers should be notified. Defaults to true. Value must be one of true or false
     */
    notifySubscribers?: pulumi.Input<boolean | undefined>;
    /**
     * Date the announcement was published
     */
    publishedAt?: pulumi.Input<string | undefined>;
    /**
     * ID of the status page the announcement was posted to
     */
    statusPageId?: pulumi.Input<string | undefined>;
    /**
     * Title of the announcement
     */
    title?: pulumi.Input<string | undefined>;
    /**
     * ID of the user who posted the announcement
     */
    userId?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a StatusPageAnnouncement resource.
 */
export interface StatusPageAnnouncementArgs {
    /**
     * Body of the announcement
     */
    body: pulumi.Input<string>;
    /**
     * Controls if status page subscribers should be notified. Defaults to true. Value must be one of true or false
     */
    notifySubscribers?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the status page the announcement was posted to
     */
    statusPageId: pulumi.Input<string>;
    /**
     * Title of the announcement
     */
    title: pulumi.Input<string>;
}
